### PR TITLE
Update the QS benchmark

### PR DESCRIPTION
**Pull request by lafita**
@josemduarte could you also update the file with the annotations?

### CODE REVIEW

**Comment by lafita** [comment]
The way I select a representative from each cluster is random, so the representatives might have changed. Is it worth that I try to select the same representatives we had in the previous version of the dataset, only adding new representatives from the new clusters?

**Comment by lafita** [comment]
I have maintained the cluster representatives where possible and added a file with all the PDB codes in each cluster. 

For some reason the cluster that contained 5a8k is not present anymore, I will try to investigate why.

**Comment by josemduarte** [comment]
Oh wait, perhaps I merged too early. Both files now contain cluster data and the benchmark results are not there anymore.

**Comment by lafita** [comment]
Sorry, I forgot to remove the cluster data from the benchmark results (but the EPPIC and PISA predictions are there). I wil submit a new PR without the cluster data in the benchmark results.

**Pull request merged**
